# Generated by Django 3.0.2 on 2020-01-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200113_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='ill',
            field=models.CharField(default='Cold', max_length=100),
        ),
    ]
    
