# Generated by Django 3.1.7 on 2021-12-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(editable=False, max_length=264, unique=True),
        ),
    ]
