# Generated by Django 3.1.7 on 2021-12-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211204_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=' /static/images/default.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
