# Generated by Django 3.1.7 on 2021-12-01 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='author',
            new_name='author_name',
        ),
    ]
